### ISSUE TITLE
Install Error unexpected T_FUNCTION

### ISSUE THREAD

**Issue by mwordpress** [ThatGerber/dfp-ads#21]
Parse error: syntax error, unexpected T_FUNCTION in /home/***/public_html/wp-content/plugins/dfp-ads/plugin.php on line 94

add_filter( 'dfp_ads_menu_position', ( function( $pos ) { return 79; }), 10 );

**Comment by ThatGerber** [comment]
You're using an unsupported version of PHP. The plugin requires PHP 5.3.0 or above to support anonymous functions.

http://php.net/manual/en/functions.anonymous.php

**Comment by mwordpress** [comment]
thanks I will verify php version :)
